[package]
name = "bamtofastq"
version = "1.0.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
docopt = "*"
rust-htslib = "*"
flate2 = "*"
rustc-serialize = "*"
shardio = { git = "ssh://git@github.com/10XDev/rust-shardio.git" }
bincode = "*"
itertools = "*"
regex = "*"
tempfile = "*"
tempdir = "*"

[dev-dependencies]
fastq_10x = { path = "../rust-fastq-10x" }
