[package]
name = "bamtofastq"
version = "1.3.0
authors = ["Patrick Marks <patrick@10xgenomics.com>"]
edition = "2018"

[dependencies]
docopt = "*"
rust-htslib = ">=0.27" 
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
shardio = { git = "https://github.com/10XGenomics/rust-shardio.git" }
bincode = "1"
itertools = ">=0.6.0"
regex = "*"
tempfile = "*"
tempdir = "*"

csv = "1.0.0"
serde = "^1.0.7"
serde_derive = "^1"
serde_bytes = "*"
ordered-float = "0.3.0"
failure = "*"
human-panic = "1"

[profile.release]
debug = 1
lto = true
