[package]
name = "bamtofastq"
version = "1.3.5"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]
edition = "2018"
resolver = "2"

[dependencies]
docopt = "*"
rust-htslib = "0.38"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
shardio = { git = "https://github.com/10XGenomics/rust-shardio.git" }
bincode = "1"
itertools = ">=0.8.0"
regex = "*"
tempfile = "*"

csv = "1.0.0"
serde = "^1.0.7"
serde_derive = "^1"
serde_bytes = "*"
failure = "*"
human-panic = "1"

[profile.release]
debug = 1
lto = true
