[package]
name = "bamtofastq"
version = "1.0.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
docopt = "*"
rust-htslib = "*"
flate2 = "*"
rustc-serialize = "*"
shardio = { path = "external/rust-shardio" }
bincode = "*"
itertools = "*"
regex = "*"
tempfile = "*"
tempdir = "*"
error-chain ="*"

[dev-dependencies]
fastq_10x = { path = "external/rust-fastq-10x" }
