[package]
name = "bamtofastq"
version = "1.0.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
docopt = "*"
rust-htslib = ">=0.12" 
flate2 = "*"
shardio = { path = "external/rust-shardio" }
bincode = "*"
itertools = ">=0.6.0"
regex = "*"
tempfile = "*"
tempdir = "*"
error-chain ="*"
csv = "1.0.0-beta.3"
serde = "1.0.7"
serde_derive = "1"
rustc-serialize = "0.3"

[dev-dependencies]
fastq_10x = { path = "external/rust-fastq-10x" }
